#!/bin/sh

### BEGIN INIT INFO
# Provides:          zbalance
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: PF_RING zc balance
# Description:       Balances PF_RING flows between flows
### END INIT INFO

. /etc/tapdance/config

NAME="zbalance"
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
APPDIR="/home/tapdance-prod/tapdance/pfring-framework/userland/examples_zc/"
APPBIN="zbalance_ipc"
APPARGS="-i $TAPDANCE_IFACES -c 99 -n $TAPDANCE_CORES -m 1 -g $TAPDANCE_ZBALANCE_CORE"
USER="root"
GROUP="root"

# Include functions 
set -e
. /lib/lsb/init-functions

start() {
  printf "Starting '$NAME'... "
  start-stop-daemon --start --quiet --chuid "$USER:$GROUP"    \
        --make-pidfile --pidfile /var/run/$NAME.pid --background       \
        --chdir "$APPDIR" \
        --startas /bin/bash -- -c "exec $APPDIR/$APPBIN $APPARGS 2>&1 | /usr/bin/multilog n100 /var/log/tapdance/zbalance/"
  printf "done\n"
}

#We need this function to ensure the whole process tree will be killed
killtree() {
    local _pid=$1
    local _sig=${2-TERM}
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child} ${_sig}
    done
    kill -${_sig} ${_pid}
}

stop() {
  printf "Stopping '$NAME'... "
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || \
  while test -d /proc/$(cat /var/run/$NAME.pid); do
    killtree $(cat /var/run/$NAME.pid) 15
    sleep 0.5
  done 
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || rm /var/run/$NAME.pid
  printf "done\n"
}

status() {
  status_of_proc -p /var/run/$NAME.pid "" $NAME && exit 0 || exit $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
